# Generated by Django 4.0.4 on 2022-05-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_genre_movie_genre_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
