# Generated by Django 4.0.4 on 2022-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='movie',
            name='coverImage',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
