# Generated by Django 4.0.4 on 2022-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_movie_cover_image_movie_coverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='coverImage',
            field=models.FileField(upload_to=''),
        ),
    ]
